name: E2E-Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test-e2e:
    name: ${{ matrix.target_features }} with Nodejs v${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          # - 10
          - 12
        os:
          - windows-latest
        target_features:
          - webpack,babel,jest
          - webpack,babel,jasmine
          - webpack,babel,mocha
          - webpack,babel,tape
          - webpack,typescript,jest
          - webpack,typescript,jasmine
          - webpack,typescript,mocha
          - webpack,typescript,tape
          - dumber,babel,jest
          - dumber,babel,jasmine
          - dumber,babel,mocha
          - dumber,babel,tape
          - dumber,typescript,jest
          - dumber,typescript,jasmine
          - dumber,typescript,mocha
          - dumber,typescript,tape
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run test:e2e
        env:
          TARGET_FEATURES: ${{ matrix.target_features }}

